//imported java class libraries
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author Mori Benjamin
 */
public class FamousFavoriteSubs2 extends javax.swing.JFrame {

//  Created an array to store the values of the menu items seleced from the dropboxes
    double [] i = new double [4];
    
    
    public FamousFavoriteSubs2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jAddress2 = new javax.swing.JTextField();
        jAddress1 = new javax.swing.JTextField();
        jTelephone = new javax.swing.JTextField();
        jCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jZip = new javax.swing.JTextField();
        jState = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTaxCheckBox = new javax.swing.JCheckBox();
        jHomeCheckBox = new javax.swing.JCheckBox();
        jRushBox = new javax.swing.JCheckBox();
        jTax = new javax.swing.JTextField();
        jHomeDelivery = new javax.swing.JTextField();
        jRush = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jSubSizeBox = new javax.swing.JComboBox();
        jBeverageBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSubTotalField = new javax.swing.JTextField();
        jTotalFeesField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTotalButton = new javax.swing.JButton();
        jTotalTaxField = new javax.swing.JTextField();
        jTotalField = new javax.swing.JTextField();
        jProcessOrderButton = new javax.swing.JButton();
        jSubBox = new javax.swing.JComboBox();
        jBreadBox = new javax.swing.JComboBox();
        jSubTotalButton = new javax.swing.JButton();
        jTotalFees = new javax.swing.JButton();
        jTotalTaxesButton = new javax.swing.JButton();
        jViewReceiptButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jReceiptField = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        setForeground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextPane1.setText("                     Welcome!\nPlease Enter Your Information Below:");
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Address1:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Address2:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("City");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Telephone (xxx-xxx-xxxx):");

        jNameField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jAddress2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jAddress1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTelephone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jCity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Zip Code");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("State");

        jZip.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jState.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTelephone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTaxCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTaxCheckBox.setText("TAX (%)");
        jTaxCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaxCheckBoxMouseClicked(evt);
            }
        });

        jHomeCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jHomeCheckBox.setText("HOME DELIVERY");
        jHomeCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHomeCheckBoxMouseClicked(evt);
            }
        });

        jRushBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRushBox.setText("RUSH");
        jRushBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRushBoxMouseClicked(evt);
            }
        });

        jTax.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTax.setText("0.00");
        jTax.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jHomeDelivery.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jHomeDelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jHomeDelivery.setText("0.00");

        jRush.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jRush.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jRush.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTaxCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jRushBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRush, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jHomeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jHomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTaxCheckBox)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jHomeCheckBox)
                    .addComponent(jHomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRushBox)
                    .addComponent(jRush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField7.setText("Please Make Your Selection.");

        jSubSizeBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jSubSizeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Size", "Regular ($4.99)", "Large ($5.99)", "Colossal ($7.99)" }));
        jSubSizeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubSizeBoxMouseClicked(evt);
            }
        });
        jSubSizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubSizeBoxActionPerformed(evt);
            }
        });

        jBeverageBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBeverageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select A Beverage ($1.00)", "Coke", "Diet Coke", "Sprite", "Root Beer", "Iced Tea" }));
        jBeverageBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBeverageBoxMouseClicked(evt);
            }
        });
        jBeverageBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeverageBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Sub:");

        jLabel7.setText("Bread:");

        jLabel8.setText("Sub Size:");

        jLabel9.setText("Beverage:");

        jSubTotalField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jSubTotalField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jSubTotalField.setText("0.00");
        jSubTotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotalFieldActionPerformed(evt);
            }
        });

        jTotalFeesField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTotalFeesField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotalFeesField.setText("0.00");

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("ORDER SUMMARY");

        jTotalButton.setFont(new java.awt.Font("Times", 0, 14)); // NOI18N
        jTotalButton.setText("Total");
        jTotalButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTotalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTotalButtonMouseClicked(evt);
            }
        });

        jTotalTaxField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTotalTaxField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotalTaxField.setText("0.00");

        jTotalField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTotalField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotalField.setText("0.00");

        jProcessOrderButton.setBackground(new java.awt.Color(255, 255, 255));
        jProcessOrderButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jProcessOrderButton.setText("Process Order");
        jProcessOrderButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jProcessOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcessOrderButtonActionPerformed(evt);
            }
        });

        jSubBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jSubBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Your Sub", "Tuna", "Barbeque Chicken", "Turkey", "Italian", "Pastrami" }));
        jSubBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubBoxMouseClicked(evt);
            }
        });
        jSubBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubBoxActionPerformed(evt);
            }
        });

        jBreadBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBreadBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Your Bread", "White", "Wheat", "Honey and Oat", "Italian Cheese", "Flat Bread" }));
        jBreadBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBreadBoxMouseClicked(evt);
            }
        });
        jBreadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreadBoxActionPerformed(evt);
            }
        });

        jSubTotalButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jSubTotalButton.setText("Order Sub Total");
        jSubTotalButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSubTotalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubTotalButtonMouseClicked(evt);
            }
        });

        jTotalFees.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTotalFees.setText("Total Fees");
        jTotalFees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTotalFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTotalFeesMouseClicked(evt);
            }
        });

        jTotalTaxesButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTotalTaxesButton.setText("Total Taxes");
        jTotalTaxesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTotalTaxesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTotalTaxesButtonMouseClicked(evt);
            }
        });

        jViewReceiptButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jViewReceiptButton.setText("View Receipt");
        jViewReceiptButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jViewReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewReceiptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSubTotalButton)
                            .addComponent(jTotalFees)
                            .addComponent(jTotalTaxesButton))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTotalFeesField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSubTotalField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTotalTaxField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSubSizeBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBeverageBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2)
                                .addComponent(jSubBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jBreadBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProcessOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jViewReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSubBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBreadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(jSubSizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBeverageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSubTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSubTotalButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTotalFees)
                        .addGap(6, 6, 6))
                    .addComponent(jTotalFeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTotalTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotalTaxesButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotalField))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProcessOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jViewReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setText("Famous Favorite Subs");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jReceiptField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jReceiptField.setText("RECEIPT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jReceiptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jReceiptField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(600, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Didn't use this method
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTaxCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaxCheckBoxMouseClicked
            /**instantiated the variables for the tax check box*/       
            double taxRate = 8.50;
            double nonRate = 0.00;
            
            //created conditional statements of the selection (or checking) the tax checkbox
            if (jTaxCheckBox.isSelected()) {
                String pTax = String.format("%.2f", taxRate);
                jTax.setText(pTax);
            }
            else {
                String noTax = String.format("%.2f", nonRate);
                jTax.setText(noTax);
            }
    }//GEN-LAST:event_jTaxCheckBoxMouseClicked

    private void jHomeCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeCheckBoxMouseClicked
            //instantiated the variables for delivery checkbox
            double hDelivery = 3.50;
            double noDelivery = 0.00;
            
            //created condiitonal statements of the selection for the Delivery fee check box
            if (jHomeCheckBox.isSelected()) {
                String dFee = String.format("%.2f", hDelivery);
                jHomeDelivery.setText(dFee);
               
            }
            else {
                String noFee = String.format("%.2f", noDelivery);
                jHomeDelivery.setText(noFee);
            }
    }//GEN-LAST:event_jHomeCheckBoxMouseClicked
  
    private void jRushBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRushBoxMouseClicked
            //instantiated the variable for rush checkbox
            double rush = 5.00;
            double noRush = 0.00;
            
            //created conditional statements of the selection for the Rush fee check boxx
            if (jRushBox.isSelected()) {
                String rushFee = String.format("%.2f", rush);
                jRush.setText(rushFee);
            }
            else {
                String noRushFee = String.format("%.2f", noRush);
                jRush.setText(noRushFee);
            }
    }//GEN-LAST:event_jRushBoxMouseClicked

    private void jBreadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreadBoxActionPerformed
        //instantiated variables of the bread selection comboBox
        
        double Choose_Your_Bread = 0.00;
        double White = 0.00;
        double Wheat = 0.00;
        double Honey_and_Oat = 0.00;
        double Italian_Cheese = 0.00;
        double Flat_Bread = 0.00;
        
        //created conditional statements for choosing the bread and puting the value in 
        //the second position of the i array
        
        if (jBreadBox.getSelectedItem().equals("White")){
            i[1] = White;

        }
        if (jBreadBox.getSelectedItem().equals("Wheat")) {
            i[1] = Wheat;
        }
        if (jBreadBox.getSelectedItem().equals("Honey and Oat")) {
            i[1] = Honey_and_Oat;
        }
        if (jBreadBox.getSelectedItem().equals("Italian Cheese")) {
            i[1] = Italian_Cheese;
        }
        if (jBreadBox.getSelectedItem().equals("Flat_Bread")) {
            i[1] = Flat_Bread;
        }
        if (jBreadBox.getSelectedItem().equals("Choose Your Bread")) {
            i[1] = Choose_Your_Bread;          
        }
    }//GEN-LAST:event_jBreadBoxActionPerformed

    private void jBreadBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBreadBoxMouseClicked

    }//GEN-LAST:event_jBreadBoxMouseClicked

    private void jSubBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubBoxActionPerformed
        //instantiated variables of the sub selection comboBox
        double Choose_Your_Sub = 0.00;
        double Tuna = 0.00;
        double Barbecue_Chicken = 0.00;
        double Turkey = 0.00;
        double Italian = 0.00;
        double Pastrami = 0.00;
        double subPrice;

        //created conditional statements for choosing the sub and puting the value in 
        //the first position of the i array
        if (jSubBox.getSelectedItem().equals("Tuna")){
            subPrice = Tuna;
            i[0] = subPrice;
        }
        if (jSubBox.getSelectedItem().equals("Barbecue Chicken")) {
            subPrice = Barbecue_Chicken;
            i[0] = subPrice;
        }
        if (jSubBox.getSelectedItem().equals("Turkey")) {
            subPrice = Turkey;
            i[0] = subPrice;
        }
        if (jSubBox.getSelectedItem().equals("Pastrami")) {
            subPrice = Italian;
            i[0] = subPrice;
        }
        if (jSubBox.getSelectedItem().equals("Italian")) {
            subPrice = Pastrami;
            i[0] = subPrice;
        }
        if (jSubBox.getSelectedItem().equals("Choose Your Sub")) {
            subPrice = Choose_Your_Sub;
            i[0] = subPrice;
        }

    }//GEN-LAST:event_jSubBoxActionPerformed

    private void jSubBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubBoxMouseClicked

    }//GEN-LAST:event_jSubBoxMouseClicked

    private void jSubTotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotalFieldActionPerformed
        
    }//GEN-LAST:event_jSubTotalFieldActionPerformed

    private void jBeverageBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeverageBoxActionPerformed
        //instantiated variables of the beverage selection comboBox
        double Select_A_Beverage = 0.00;
        double Drink = 1.00;
        double drinkPrice;
        
        //created conditional statements for choosing the beverage and puting the value in 
        //the forth position of the i array
        if (jBeverageBox.getSelectedItem().equals("Coke")){
            drinkPrice = Drink;
            i[3] = drinkPrice;
        }
        if (jBeverageBox.getSelectedItem().equals("Diet Coke")) {
            drinkPrice = Drink;
            i[3] = drinkPrice;
        }
        if (jBeverageBox.getSelectedItem().equals("Sprite")) {
            drinkPrice = Drink;
            i[3] = drinkPrice;
        }
        if (jBeverageBox.getSelectedItem().equals("Root Beer")) {
            drinkPrice = Drink;
            i[3] = drinkPrice;
        }
        if (jBeverageBox.getSelectedItem().equals("Iced Tea")) {
            drinkPrice = Drink;
            i[3] = drinkPrice;
        }
        if (jBeverageBox.getSelectedItem().equals("Select A Beverage ($1.00)")) {
            drinkPrice = Select_A_Beverage;
            i[3] = drinkPrice;
        }
    }//GEN-LAST:event_jBeverageBoxActionPerformed

    private void jBeverageBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBeverageBoxMouseClicked

    }//GEN-LAST:event_jBeverageBoxMouseClicked

    private void jSubSizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubSizeBoxActionPerformed
        //instantiated variables of the Bread selection comboBox
        double Select_Size = 0.00;
        double Regular = 4.99;
        double Large = 5.99;
        double Colossal = 7.99;
       
        //created conditional statements for choosing the sub size and puting the value in 
        //the third position of the i array
        if (jSubSizeBox.getSelectedItem().equals("Regular ($4.99)")){
            i[2] = Regular;
        }
        if (jSubSizeBox.getSelectedItem().equals("Large ($5.99)")) {
            i[2] = Large;
        }
        if (jSubSizeBox.getSelectedItem().equals("Colossal ($7.99)")) {
            i[2] = Colossal;
        }
        if (jSubSizeBox.getSelectedItem().equals("Select Size")) {
            i[2] = Select_Size;
      }
        
    }//GEN-LAST:event_jSubSizeBoxActionPerformed

    private void jSubSizeBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubSizeBoxMouseClicked

    }//GEN-LAST:event_jSubSizeBoxMouseClicked

    private void jTotalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTotalButtonMouseClicked
        //instantiated variables of the subtotal categories
        //while converting the string to doubles
        double cTotal1 = Double.parseDouble(jSubTotalField.getText());
        double cTotal2 = Double.parseDouble(jTotalFeesField.getText());
        double cTotal3 = Double.parseDouble(jTotalTaxField.getText());
        
        //instantiate variable for summing the subtotal categories
        double total = (cTotal1 + cTotal2 + cTotal3);
        
        //taking the total values and converting it to a string
        String iTotal = String.format("$ %.2f", total);
        jTotalField.setText(iTotal);
    }//GEN-LAST:event_jTotalButtonMouseClicked

    private void jSubTotalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubTotalButtonMouseClicked
        //instantiated sub total variable of the menu the items selected
        //while converting the string to doubles    
        double subtotal;
        
        //instantiate variable for summing the menu items
        subtotal = i[0] + i[1] + i[2] + i[3];
        
        //taking the subtotal value and converting it to a string        
        String pSubT = String.format("%.2f", subtotal);
        jSubTotalField.setText(pSubT);
        
        
    }//GEN-LAST:event_jSubTotalButtonMouseClicked

    private void jTotalFeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTotalFeesMouseClicked
            //instantiated sub total variable of the fees
            //while converting the string to doubles   
            double rushTotal = Double.parseDouble(jRush.getText());
            double deliveryTotal = Double.parseDouble(jHomeDelivery.getText());
            
            //instantiate variable for summing the fees
            double totalFees = (rushTotal + deliveryTotal);
            
            //taking the total fees and converting it to a string
            String tFees = String.format("%.2f", totalFees);
            jTotalFeesField.setText(tFees);
    }//GEN-LAST:event_jTotalFeesMouseClicked

    private void jTotalTaxesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTotalTaxesButtonMouseClicked
            //instantiated sub total variable of sub totals and the tax multiplyer
            //while converting the string to doubles   
            double subTotal = Double.parseDouble(jSubTotalField.getText());
            double allFees = Double.parseDouble(jTotalFeesField.getText());
            double multiplier = Double.parseDouble(jTax.getText());
            
            //instantiate variable for calculating total tax amounts
            double totalTaxes = ((subTotal + allFees) * multiplier) / 100;
            
            //taking the total taxes and converting it to a string
            String allTaxes = String.format("%.2f", totalTaxes);
            jTotalTaxField.setText(allTaxes);
           
    }//GEN-LAST:event_jTotalTaxesButtonMouseClicked

    private void jProcessOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcessOrderButtonActionPerformed
        //instantiating variables taken from every texfield
        //and converting them to strings 
        String name = jNameField.getText();
        String address1 = jAddress1.getText();
        String address2 = jAddress2.getText();
        String city = jCity.getText();
        String state = jState.getText();
        String zip = jZip.getText();
        String phone = jTelephone.getText();

        String sub =  (String) jSubBox.getSelectedItem();
        String bread = (String) jBreadBox.getSelectedItem();
        String size = (String) jSubSizeBox.getSelectedItem();
        String drink = (String) jBeverageBox.getSelectedItem();

        String subTotal = jSubTotalField.getText();
        String totalFees = jTotalFeesField.getText();
        String totalTax = jTotalTaxField.getText();
        String totalAll = jTotalField.getText();
        
        //throwing an exception 
        try {
            
            //using io. methods to write to a file on my computer and giving
            //the file a name--SubOrder.txt
            FileWriter stream = new FileWriter("/users/Mori/Documents/subOrder.txt");
            
            //Streaming the text in the text fields to the file
            BufferedWriter out = new BufferedWriter(stream);
            
            //writing to the file
            out.write("CUSTOMER INFORMATION   \n\n");
            out.write("Name: " + name + "\n");
            out.write("Address1: " + address1 + "\n");
            out.write("Address2: " + address2 + "\n");
            out.write("City: " + city + "\n");
            out.write("State: " + state + "\n");
            out.write("Zip: " + zip + "\n");
            out.write("Telephone:  " + phone + "\n\n\n");
            out.write("ORDER SUMMARY  \n\n");
            out.write("Sub:  " + sub + "\n");
            out.write("Bread:  " + bread + "\n");
            out.write("Size:  " + size + "\n");
            out.write("Beverage:  " + drink + "\n\n\n");
            out.write("BILL SUMMARY   \n\n");
            out.write("Sub Tota: " + subTotal + "\n");
            out.write("Total Fees:  " + totalFees + "\n");
            out.write("Tax:  " + totalTax + "\n");
            out.write("TOTAL:  " + totalAll  + "\n\n");
            out.write("Thank You " + name + " for choosing Favorite Famous Subs!");
            
            //stop writing to the file
            out.close();
            
            //cathing the exception
        } catch (Exception ev) {}

    }//GEN-LAST:event_jProcessOrderButtonActionPerformed

    private void jViewReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewReceiptButtonActionPerformed
            //throwing exception
            try {
            FileReader file = new FileReader("/users/Mori/Documents/subOrder.txt");
            BufferedReader reader = new BufferedReader(file);
            
            jTextArea1.read (reader,null);
            reader.close();
            jTextArea1.requestFocus();
           
         //catch the exception and print to the textarea  
       } catch (Exception e){
            
    }

    }//GEN-LAST:event_jViewReceiptButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //method for closing the jFrame
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed
            
            
               
                
            
    
                
            
            
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamousFavoriteSubs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamousFavoriteSubs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamousFavoriteSubs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamousFavoriteSubs2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FamousFavoriteSubs2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddress1;
    private javax.swing.JTextField jAddress2;
    private javax.swing.JComboBox jBeverageBox;
    private javax.swing.JComboBox jBreadBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCity;
    private javax.swing.JCheckBox jHomeCheckBox;
    private javax.swing.JTextField jHomeDelivery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNameField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jProcessOrderButton;
    private javax.swing.JTextField jReceiptField;
    private javax.swing.JTextField jRush;
    private javax.swing.JCheckBox jRushBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jState;
    private javax.swing.JComboBox jSubBox;
    private javax.swing.JComboBox jSubSizeBox;
    private javax.swing.JButton jSubTotalButton;
    private javax.swing.JTextField jSubTotalField;
    private javax.swing.JTextField jTax;
    private javax.swing.JCheckBox jTaxCheckBox;
    private javax.swing.JTextField jTelephone;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jTotalButton;
    private javax.swing.JButton jTotalFees;
    private javax.swing.JTextField jTotalFeesField;
    private javax.swing.JTextField jTotalField;
    private javax.swing.JTextField jTotalTaxField;
    private javax.swing.JButton jTotalTaxesButton;
    private javax.swing.JButton jViewReceiptButton;
    private javax.swing.JTextField jZip;
    // End of variables declaration//GEN-END:variables
   
}